server:
  port: 9070
  address: 127.0.0.1
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        same-site: strict

camel:
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
  servlet:
    mapping:
      context-path: "/api/*"

fhir:
  server-url: https://localhost:8090/baseR4

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  health:
    show-details: always

spring:
  jmx:
    enabled: true
  security:
    user:
      roles: admin,viewer
  artemis:
    mode: EMBEDDED
    host: localhost
    port: 61616
    user: myuser
    password: mypass

hawtio:
  authenticationEnabled: false

logging:
  file:
    name: oauth-route-middleware.log
