services:
  dhis2:
    image: "${DHIS2_IMAGE:-dhis2/core:40.5.0}"
    restart: unless-stopped
    volumes:
      - ./config/dhis2/dhis.conf:/opt/dhis2/dhis.conf:ro
    environment:
      JAVA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}' \
              -Dlog4j2.configurationFile=/opt/dhis2/log4j2.xml"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -S -O /dev/null http://127.0.0.1:8080/dhis-web-commons/security/login.action 2>&1| grep -q 'HTTP.*200'"]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  db:
    image: ghcr.io/baosystems/postgis:13-3.4
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5

  gateway:
    image: nginx
    restart: always
    depends_on:
      dhis2:
        condition: service_healthy
    ports:
      - "${DHIS2_PORT:-8080}:80"
    volumes:
      - ./config/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    security_opt:
      - no-new-privileges:true
  
  civil-registry:
    image: "hapiproject/hapi:v7.4.0-tomcat"
    volumes:
      - ./config/civil-registry/server.xml:/opt/bitnami/apache-tomcat/conf/server.xml:ro
      - ./config/civil-registry/localhost-rsa-cert.pem:/opt/bitnami/apache-tomcat/conf/localhost-rsa-cert.pem:ro
      - ./config/civil-registry/localhost-rsa-key.pem:/opt/bitnami/apache-tomcat/conf/localhost-rsa-key.pem:ro
    ports:
      - "8090:8080"  
  
  # oauth-route-middleware:
  #   build: ./oauth-route-middleware
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true


volumes:
  db-dump: { }
  files:
    driver: local
  postgresql:
    driver: local
