name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test oauth-route-middleware
        run: mvn -B clean test
        working-directory: ./oauth-route-middleware
      - name: Test docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1